<?xml version="1.0"?>
<package format="3">
  <name>joy_teleop_hiddi</name>
  <version>1.0.0</version>
  <description>Reads a Logitech F310/F710 via io-hid and publishes sensor_msgs/Joy messages.</description>
  <maintainer email="nirajpatel@qnx.com">user</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
 
  <build_depend>builtin_interfaces</build_depend>
  <build_depend>rclcpp</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <exec_depend>builtin_interfaces</exec_depend>
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
 
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
